on: [push, pull_request]

name: rustfmt/cargo check

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name:                   Run cargo check 1
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --no-default-features --all
      - name:                   Run cargo check 2
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --all
      - name:                   Run cargo check benches
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked -p ethcore --benches
